local api = vim.api
-- api.nvim_set_keymap("n", "<leader>m", ":Mark<cr>", {noremap=true})
-- api.nvim_create_user_command("Mark", function(args)
--
-- 	local mode = api.nvim_get_mode()
-- 	vim.print(mode)
-- 	-- local buf = api.nvim_get_current_buf()
-- 	-- local hl = ""
-- 	-- if mode == "n" then
-- 	-- 	api.nvim_buf_add_highlight(buf, 0, hl, args.line1, 0, -1)
-- 	-- else
-- 	-- 	local st = vim.fn.getpos("v")
-- 	-- 	local ed = vim.fn.getpos("'>")
-- 	-- 	if args.range == 1 then
-- 	-- 		api.nvim_buf_add_highlight(buf, 0, hl, args.line1, st[3], ed[3])
-- 	-- 	end
-- 	-- end
-- end, { range = true })
