-- return {
-- 	"p00f/alabaster.nvim",
-- 	config = function()
-- 		vim.cmd.colorscheme([[alabaster]])
-- 	end,
-- }
-- local bg = "#f7f7f7"
-- local fg = "#000000"
-- local punct_fg = "#777777"
-- local def_fg = "#325cc0"
-- local const_fg = "#7a3e9d"
-- local active = "#ffbc5d"
-- local active_blue = "#007acc"
-- local string_fg = "#448c27"
-- local darker_fg = "#7d7d7d"
-- local diffadd = "#284918"
-- local diffdelete = "#B40600"
-- local diffchange = "#ec8013"
-- local statusline = "#c9c9c9"
-- local comment = "#aa3731"
-- local dim_comment = "#696969"

-- local bg = "#0e1415"
-- local fg = "#cecece"
-- local punct_fg = "#708b8d"
-- local def_fg = "#71ade7"
-- local const_fg = "#cc8bc9"
-- local active = "#cd974b"
-- local string_fg = "#95cb82"
-- local darker_fg = "#7d7d7d"
-- local diffadd = "#6abf40"
-- local diffdelete = "#d2322d"
-- local diffchange = "#ec8013"
-- local statusline = "#162022"
-- local comment = "#dfdf8e"
-- local dim_comment = "#696969"
-- return {
-- 	"RRethy/base16-nvim",
-- 	config = function()
-- 		require("base16-colorscheme").setup(
-- 			-- {
-- 			-- base00 = "#ffffff",
-- 			-- base01 = "#ffffd7",
-- 			-- base02 = "#ffffff",
-- 			-- base03 = "#000000",
-- 			-- base04 = "#000000",
-- 			-- base05 = "#000000", -- text
-- 			-- base06 = "#ffffff",
-- 			-- base07 = "#ffffd7",
-- 			-- base08 = "#181818",
-- 			-- base09 = "#181818",
-- 			-- base0A = "#151670",
-- 			-- base0B = "#1d3901",
-- 			-- base0C = "#195015",
-- 			-- base0D = "#000000",
-- 			-- base0E = "#151070",
-- 			-- base0F = "#ff0303",
-- 			-- }
-- 		)
-- 	end,
-- }
-- return {
-- 	{
-- 		"nvchad/ui",
-- 		config = function()
-- 			vim.g.base46_cache = vim.fn.stdpath("data") .. "/base46_cache/"
-- 			require("nvchad")
-- 		end,
-- 	},
--
-- 	{
-- 		"nvchad/base46",
-- 		lazy = true,
-- 		build = function()
-- 			require("base46").load_all_highlights()
-- 			dofile(vim.g.base46_cache .. "defaults")
-- 			dofile(vim.g.base46_cache .. "statusline")
-- 		end,
-- 	},
--
-- 	"nvchad/volt", -- optional, needed for theme switcher
-- 	-- or just use Telescope themes
-- }
return {
	"EdenEast/nightfox.nvim",
	config = function()
		vim.cmd.colorscheme("carbonfox")
	end,
}

--return {
--	"projekt0n/github-nvim-theme",
--	lazy = false, -- make sure we load this during startup if it is your main colorscheme
--	priority = 1000, -- make sure to load this before all the other start plugins
--	config = function()
--		require("github-theme").setup({
--			-- ...
--		})
--
--		vim.cmd("colorscheme github_dark_hight_contrast")
--	end,
--}

--return {
--	"Abstract-IDE/Abstract-cs",
--	lazy = false,
--	priority = 1000,
--	config = function()
--		vim.cmd.colorscheme("abscs")
--	end,
--}
--return {
--	"gmr458/cold.nvim",
--	lazy = false,
--	priority = 1000,
--	build = ":ColdCompile",
--	config = function()
--		require("cold").setup({
--			transparent_background = false,
--		})
--		vim.cmd.colorscheme("cold")
--	end,
--}
--  return {
--  	"bluz71/vim-moonfly-colors",
--  	name = "moonfly",
--  	lazy = false,
--  	priority = 1000,
--  	config = function()
--  		vim.cmd [[colorscheme moonfly]]
--  	end,
--  }
-- return {
-- 	"rebelot/kanagawa.nvim",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		vim.cmd.colorscheme("kanagawa-dragon")
-- 		-- vim.cmd("colorscheme kanagawa-wave")
-- 	end,
-- }
