return {}
--return {
--	"stevearc/oil.nvim",
--	config = function()
--		require("oil").setup({
--			default_file_explorer = false,
--			skip_confirm_for_simple_edits = true,
--			keymaps = {
--				["<Down>"] = "actions.select",
--				["<Up>"] = "actions.parent",
--			},
--		})
--	end,
--}
